import {store} from '../Reducers/CombineReducers';
import {selectorContainingColorsAndGameStatus} from '../Selectors/GameSelectors';

export const assertEquality = () => {
// Here we check that the colors so far  chosen by the player
// are equal to those generated by the computer.
    const {limit, equality, partialEquality, generalStatus} = selectorContainingColorsAndGameStatus(store.getState());
    const {strict} = generalStatus;
    if (equality) {
        if (limit === 20) {
            return 'victory';
        }
        return 'equality';
    } else if (partialEquality) {
        return 'partialEquality';

    } else if (!partialEquality && strict) {
        return 'gameOver';
    } else {
        return 'COLOR_REPLAY';
    }

};
